name: 📚 Documentation
description: Report an issue related to https://flxst.github.io/nerblackbox/
labels: [ "documentation" ]

body:
  - type: textarea
    attributes:
      label: 📚 The doc issue
      description: >
        A clear and concise description of what content in https://flxst.github.io/nerblackbox/ is an issue.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Suggest a potential alternative/fix
      description: >
        Tell us how we could improve the documentation in this regard.

  - type: markdown
    attributes:
      value: >
        Thanks for contributing 🎉!