site_name: nerblackbox
theme:
  name: material
  palette:
    primary: black
  features:
    - navigation.tabs
    - toc.integrate
  favicon: images/package-16.svg
  icon:
    logo: octicons/package-16
copyright: Copyright &copy; 2020 - 2021 Arbetsförmedlingen (Felix Stollenwerk)
plugins:
  - mkdocstrings
  - search
# repo_url: https://github.com/af-ai-center/nerblackbox
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - mkdocs-click
extra_css:
  - stylesheets/extra.css
nav:
    - Overview: 'index.md'
    - Guide:
      - 'guide/getting_started.md'
      - 'guide/custom_experiments.md'
      - 'guide/datasets_and_models.md'
    - API Documentation:
      - Command Line Interface: 'api_documentation/cli.md'
      - Python API:
        - Overview: 'api_documentation/python_api/overview.md'
        - 'api_documentation/python_api/nerblackbox.md'
        - 'api_documentation/python_api/experiment_results.md'
        - 'api_documentation/python_api/experiments_results.md'
        - 'api_documentation/python_api/ner_model_predict.md'
