site_name: nerblackbox
theme:
  name: material
  palette:
    primary: black
  features:
    - navigation.tabs
    - toc.integrate
  favicon: images/package-16.svg
  icon:
    logo: octicons/package-16
copyright: Copyright &copy; 2021 - 2023 Felix Stollenwerk
plugins:
  - mkdocstrings
  - search
# repo_url: https://github.com/flxst/nerblackbox
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - mkdocs-click
extra_css:
  - stylesheets/extra.css
nav:
    - Start: 'index.md'
    - Preparation: 'preparation.md'
    - Data: 'data.md'
    - Training: 'training.md'
    - Evaluation: 'evaluation.md'
    - Inference: 'inference.md'
    - Advanced:
        - 'advanced/compatibility_with_huggingface.md'
        - 'advanced/reproduction_of_results.md'
        - 'advanced/text_encoding.md'
    - Python API:
      - Overview: 'python_api/overview.md'
      - 'python_api/store.md'
      - 'python_api/dataset.md'
      - 'python_api/experiment.md'
      - 'python_api/model.md'
      - 'python_api/annotation_tool.md'
      - 'python_api/text_encoder.md'
    - CLI: 'cli.md'
